### PR TITLE
Regenerate html and pdf outputs for Lecture 3

### PR DESCRIPTION
**Pull request by petrblaho**

### CODE REVIEW

**Comment by etingof** [comment]
Thanks for building the .pdf!

Is it possible to paginate it like one slide per page? I am worrying how we would go though undivided slides at the presentation time...

**Comment by petrblaho** [comment]
@etingof for presentation we should use html file with slides using reveal.js

**Comment by petrblaho** [comment]
Rebased after merged #7

**Comment by petrblaho** [comment]
Rebased after lates changes in master

**Pull request merged**
